name: Deploy Flask App to Touge Server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: requirements.txt
      - name: Install dependencies and run tests
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest==8.4.1
          pytest tests/ -v
        continue-on-error: false
      - name: Deploy to Touge Server via SSH (Port 51279)
        run: |
          mkdir -p ~/.ssh
          printf "%s\n" "${{ secrets.TOUGE_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 51279 -H ${{ secrets.TOUGE_SERVER_IP }} >> ~/.ssh/known_hosts
          echo "SSH 环境配置完成，开始连接服务器..."
          ssh -v -p 51279 -o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedAlgorithms=+ssh-rsa root@${{ secrets.TOUGE_SERVER_IP }} << 'EOF'
            set -e
            echo "===== 部署流程开始 ====="
            echo "当前用户: $(whoami), 主机: $(hostname)"
            cd /root/flask-web-app || { echo "项目目录不存在，创建并进入"; mkdir -p /root/flask-web-app && cd /root/flask-web-app; }
            echo "拉取最新代码..."
            git pull origin main || { echo "Git 拉取失败"; exit 1; }
            echo "安装依赖..."
            pip3 install --upgrade pip
            pip3 install -r requirements.txt || { echo "依赖安装失败"; exit 1; }
            echo "重启服务..."
            supervisorctl restart flask-web-app || { echo "服务重启失败"; exit 1; }
            echo "服务状态: $(supervisorctl status flask-web-app)"
            echo "===== 部署流程结束 ====="
          EOF
        env:
          TOUGE_SSH_PRIVATE_KEY: ${{ secrets.TOUGE_SSH_PRIVATE_KEY }}
          TOUGE_SERVER_IP: ${{ secrets.TOUGE_SERVER_IP }}
